package com.endoflineblog.truffle.part_04;

import com.endoflineblog.truffle.part_04.nodes.AdditionNode;
import com.endoflineblog.truffle.part_04.nodes.EasyScriptNode;
import com.endoflineblog.truffle.part_04.nodes.IntLiteralNode;
import org.antlr.v4.runtime.BailErrorStrategy;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.TerminalNode;

import java.io.IOException;
import java.io.Reader;

/**
 * This the parser class that turns EasyScript code into the equivalent
 * {@link EasyScriptNode Truffle AST from part 3}.
 * It uses classes generated by the ANTLR Gradle plugin,
 * {@link EasyScriptLexer} and {@link EasyScriptParser},
 * from the grammar file specified in src/main/antlr/com/endoflineblog/truffle/part_04/EasyScript.g4.
 *
 * @see #parse(String)
 * @see #parse(Reader)
 */
public final class EasyScriptTruffleParser {
    public static EasyScriptNode parse(String program) {
        return parse(CharStreams.fromString(program));
    }

    public static EasyScriptNode parse(Reader program) throws IOException {
        return parse(CharStreams.fromReader(program));
    }

    private static EasyScriptNode parse(CharStream inputStream) {
        var lexer = new EasyScriptLexer(inputStream);
        // remove the default console error listener
        lexer.removeErrorListeners();
        var parser = new EasyScriptParser(new CommonTokenStream(lexer));
        // remove the default console error listener
        parser.removeErrorListeners();
        // throw an exception when a parsing error is encountered
        parser.setErrorHandler(new BailErrorStrategy());
        EasyScriptParser.ExprContext context = parser.start().expr();
        return parseExpr(context);
    }

    private static EasyScriptNode parseExpr(EasyScriptParser.ExprContext expr) {
        return expr instanceof EasyScriptParser.AddExprContext
                ? parseAdditionExpr((EasyScriptParser.AddExprContext) expr)
                : parseLiteral((EasyScriptParser.LiteralExprContext) expr);
    }

    private static AdditionNode parseAdditionExpr(EasyScriptParser.AddExprContext addExpr) {
        return new AdditionNode(
                parseExpr(addExpr.left),
                parseExpr(addExpr.right)
        );
    }

    private static EasyScriptNode parseLiteral(EasyScriptParser.LiteralExprContext literalExpr) {
        TerminalNode intTerminal = literalExpr.literal().INT();
//        return intTerminal != null
//                ? parseIntLiteral(intTerminal.getText())
//                : parseDoubleLiteral(literalExpr.getText());
        return parseIntLiteral(intTerminal.getText());
    }

    private static EasyScriptNode parseIntLiteral(String text) {
        return new IntLiteralNode(Integer.parseInt(text));
//        try {
//            return new IntLiteralNode(Integer.parseInt(text));
//        } catch (NumberFormatException e) {
//            // it's possible that the integer literal is too big to fit in a 32-bit Java `int` -
//            // in that case, fall back to a double literal
//            return parseDoubleLiteral(text);
//        }
    }

//    private static DoubleLiteralNode parseDoubleLiteral(String text) {
//        return new DoubleLiteralNode(Double.parseDouble(text));
//    }
}
