plugins {
    id 'antlr'
    id 'me.champeau.jmh' version '0.7.3'
    id 'application'
}

dependencies {
    antlr "org.antlr:antlr4:$antlr_version"
    implementation "org.graalvm.js:js:$graal_version"
    implementation "org.graalvm.polyglot:profiler:$graal_version"
    implementation "org.graalvm.polyglot:inspect:$graal_version"
    implementation "org.apache.commons:commons-text:1.14.0"

    testImplementation "org.graalvm.truffle:truffle-tck:$graal_version"
}

String jmhIncludes = findProperty("jmhIncludes")
jmh {
    if (jmhIncludes != null) {
        includes = [jmhIncludes]
    }
}

application {
    mainClass = 'com.endoflineblog.truffle.part_17.Main'
}
