plugins {
    id 'antlr'
    id 'me.champeau.jmh' version '0.7.3'
}

dependencies {
    antlr "org.antlr:antlr4:$antlr_version"
    implementation "org.graalvm.js:js:$graal_version"
    implementation "org.graalvm.truffle:truffle-sl:$graal_version"
}

String jmhIncludes = findProperty("jmhIncludes")
jmh {
    if (jmhIncludes != null) {
        includes = [jmhIncludes]
    }
}
