name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # disable the demon, as it's causing some problems
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - uses: actions/checkout@v2

      - name: Set up GraalVM with Java 11
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.3.1'
          java-version: '11'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and test the project (all parts)
        run: ./gradlew build
